application: tstromberg-blog
version: 1
runtime: go
api_version: go1

handlers:
- url: /third_party
  static_dir: third_party

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: _go_app
